version: "3"
services:
  galaxy:
    image: bgruening/galaxy-stable
    hostname: galaxy
    domainname: local
    ports:
    # FTP Upload
    # - "8021:21"
    # ??
    # - "8022:22"
    # Webserver
    - "8080:80"
    # supvisord web app
    - "9002:9002"
    volumes:
      # Stat is entirely in /export. Enable for debug purposes
      - ./export:/export
      - ./custom_tools:/custom_tools
      - ./custom_config:/custom_config
      # PLACEHOLDER_VOLUMES
    environment:
      - GALAXY_CONFIG_TOOL_CONFIG_FILE=/custom_tools/custom_tool_conf.xml
      # PLACEHOLDER_ENV

  galaxy-script:
    build: .
