version: "3"
services:
  davrods:
    build:
      context: .
      args:
        host_owner_uid: ${DAVRODS_VOLUME_OWNER}

    networks:
      - irods_default
    ports:
      - 80:80
    volumes:
      - ./volumes/davrods-vhost.conf:/etc/apache2/sites-available/davrods-vhost.conf
      - ./volumes/irods_environment.json:/etc/apache2/irods/irods_environment.json

networks:
  irods_default:
    external: true
