galaxy:
  url: "http://galaxy.uni.andreas-sk.de"
  admin_key: "supersecrtetadminkey"
  ssh_key: /Users/ASkorczyk/...

destinations:
  - name: LocalPulsar
    type: PulsarMQ
    amqp_url: "user:password@rabbitmq.uni.andreas-sk.de"
  - name: Freiburg
    type: PulsarMQ
    amqp_url: "user:password@pulsar.galaxy.uni-freiburg.de"
  - name: Italy
    type: PulsarMQ
    amqp_url: "user:password@pulsar.galaxy.italy"
  - name: LocalCondor
    type: Condor
  - name: CondorWithGalaxy
    type: GalaxyCondor

workflows:
  - name: gromacs
    type: Galaxy
    path: training/computational-chemistry/bio3danalysis/gromacs.ga
    description: BlaBlaBla
  - name: mapping_by_sequencing
    type: Galaxy
    path: training/variant-analysis/mapping-by-sequencing/mapping_by_sequencing.ga
    description: BlaBlaHahaha

benchmarks:
  - name: Benchmark1
    type: ColdvsWarm
    destinations:
      - LocalPulsar
    runs_per_workflow: 5
    workflows:
      - gromacs
      - mapping_by_sequencing
    additional_settings:
      cold_pre_task: "ansible-playbook cleanup-pulsar.yml" # CleanUp Pulsar for cold test
      warm_pre_task: "ansible-playbook cleanup-pulsar.yml"
  - name: Benchmark2
    type: DestinationsComparison
    pre_task: "./benchmark2_pre-task.sh" # Call some script before starting benchmark
    post_task: "./benchmark2_post-task.sh" # Call some script after ending benchmark (like for cleaning up)
    destinations:
      - LocalPulsar
      - Freiburg
      - Italy
    workflows:
      - gromacs
      - mapping_by_sequencing
  - name: Benchmark3
    type: Burst
