version: "3"
services:
  benchmarker:
    build: .
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - type: bind
        source: .
        target: /src
      - type: bind
        source: ${SSH_AUTH_SOCK}
        target: /ssh-agent
      - type: bind
        source: ${HOME}/.ssh
        target: /root/.ssh-host
        read_only: true
    working_dir: /src

    command: [
      "--cfg",
      "examples/05_benchmark_posix.yml",
    ]
