version: "3"
services:
  benchmarker:
    build: .
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - type: bind
        source: .
        target: /src
      - type: bind
        source: ${SSH_AUTH_SOCK}
        target: /ssh-agent
      - type: bind
        source: ${HOME}/.ssh
        target: /root/.ssh-host
        read_only: true
    working_dir: /src

    command: [
      "--cfg",
      "examples/06_benchmark_galaxy_1x0.yml",
      "examples/06_benchmark_galaxy_1x1K.yml",
      "examples/06_benchmark_galaxy_10x1K.yml",
      "examples/06_benchmark_galaxy_100x1K.yml",
      "examples/06_benchmark_galaxy_1000x1K.yml",
      "examples/06_benchmark_galaxy_10000x1K.yml",
      "examples/06_benchmark_galaxy_1x1M.yml",
      "examples/06_benchmark_galaxy_1x1G.yml",
      "examples/06_benchmark_galaxy_1x10G.yml",
    ]
