---
- name: Stop container
  community.docker.docker_compose:
    project_src: /irods
    state: absent
    build: yes

- name: Remove files from server
  file:
    path: /irods
    state: absent

- name: Remove irods volume
  file:
    path: "{{ irods_volume }}/irods"
    state: absent
