- hosts: all
  become: yes
  handlers:
    - name: restart galaxy
      supervisorctl:
        name: galaxy
        state: restarted
  tasks:
    - name: Copy pulsar_actions.yml
      copy:
        src: galaxy_files/pulsar_actions.yml
        dest: "{{ galaxy_config_dir }}/pulsar_actions.yml"
        owner: "{{ galaxy_user }}"
        group: "{{ galaxy_user }}"
      notify: restart galaxy
    - name: Copy job_conf.xml
      copy:
        src: galaxy_files/job_conf.xml.tmp
        dest: "{{ galaxy_config_dir }}/job_conf.xml"
        owner: "{{ galaxy_user }}"
        group: "{{ galaxy_user }}"
      notify: restart galaxy
    - name: Copy dynamic_destination.py
      copy:
        src: galaxy_files/dynamic_destination.py
        dest: "{{ galaxy_root_path }}/server/lib/galaxy/jobs/rules/dynamic_destination.py"
        owner: "{{ galaxy_user }}"
        group: "{{ galaxy_user }}"
      notify: restart galaxy
    - name: Copy JobStatus-MetricPlugin
      copy:
        src: galaxy_files/job_status.py
        dest: "{{ galaxy_root_path }}/server/lib/galaxy/jobs/metrics/instrumenters/job_status.py"
        owner: "{{ galaxy_user }}"
        group: "{{ galaxy_user }}"
      notify: restart galaxy
    - name: Copy StagingTime-MetricPlugin
      copy:
        src: galaxy_files/staging_time.py
        dest: "{{ galaxy_root_path }}/server/lib/galaxy/jobs/metrics/instrumenters/staging_time.py"
        owner: "{{ galaxy_user }}"
        group: "{{ galaxy_user }}"
      notify: restart galaxy
    - name: Copy job_metrics_conf.yml
      copy:
        src: galaxy_files/job_metrics_conf.xml
        dest: "{{ galaxy_config_dir }}/job_metrics_conf.xml"
        owner: "{{ galaxy_user }}"
        group: "{{ galaxy_user }}"
      notify: restart galaxy
