- hosts: "{{ host }}"
  tasks:
    - name: Check if galaxy directory exist
      stat:
        path: "/galaxy"
      register: stat_output
      failed_when: not stat_output.stat.isdir

    - name: Run script inside galaxy-script container
      community.docker.docker_container_exec:
        container: galaxy_galaxy-script_1
        command: python run_job.py
        env:
          GLX_TOOL_ID: "{{ glx_tool_id }}"
          GLX_TOOL_INPUT: "'{{ glx_tool_input }}'"
      register: job_result

    - name: debug
      debug: var=job_result

    - name: Save results
      local_action:
        module: copy
        content: "{{ job_result }}"
        dest: "{{ controller_dir }}/{{ glx_result_file }}"
