- hosts: "{{ host }}"
  become: true
  tasks:
    - name: Copy container setup onto host (sychronize preserves file permissions)
      synchronize:
        src: ./files/irods-webdav-client/
        dest: /irods
        recursive: yes

    - name: Setup fstab
      template:
        src: ./files/irods-webdav-client/volumes/fstab.j2
        dest: /irods/volumes/fstab

    - name: Create irods volume
      file:
        path: "{{ irods_host_volume }}/irods-webdav"
        state: directory
        owner: "{{ davrods_owner_uid }}"
        group: "{{ davrods_owner_uid }}"
        mode: '0755'

    - name: Build and start container
      community.docker.docker_compose:
        project_src: /irods
        state: present
        build: yes
      environment:
        IRODS_HOST_VOLUME: "{{ irods_host_volume }}"
        IRODS_HOST_VOLUME_OWNER: "{{ davrods_owner_uid }}"
      register: output

    # - name: Debug startup logs
    #   command: docker logs irods_irods-fuse_1
    #   register: logoutput

    # - name: debug
    #   debug: var=output

    - name: "Check 'Build and start container'"
      ansible.builtin.assert:
        that:
          - "output.services['irods-webdav']['irods_irods-webdav_1'].state.running"
