- hosts: all
  tasks:
    - name: Create test directory
      file:
        path: "{{ fio_dir }}/fio_in_progress"
        state: directory

    - name: Execute the fio test
      ansible.builtin.command:  "fio --rw={{ fio_mode }} --name={{ fio_jobname }}
      --bs={{ fio_blocksize }} --direct=1 --numjobs={{ fio_numjobs }}
      --ioengine=libaio --iodepth={{ fio_iodepth }} --refill_buffers
      --group_reporting --runtime=60 --time_based --size=5G
      --output-format=json --filename=testfile.fio --output {{ fio_result_file }}"
      args:
        chdir: "{{ fio_dir }}/fio_in_progress"
      become: yes
      register: fio_status

    - name: Collect result
      ansible.builtin.fetch:
        src: "{{ fio_dir }}/fio_in_progress/{{ fio_result_file }}"
        dest: "{{ controller_dir }}/{{ fio_result_file }}"
        flat: yes

    - name: Cleanup
      file:
        path: "{{ fio_dir }}/fio_in_progress"
        state: absent